services:
  webserv:
    container_name: webserv
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./website/:/webserv/website:ro
    command: ["./webserv", "config/config.json"]