services:
  webserv:
    container_name: webserv
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    # volumes:
    #   # - .:/webserv:ro
    #   - ./website/:/webserv/website:ro
    command: ["./webserv", "config/config.json"]